CC = gcc
FC = gfortran
RM = rm
INCLUDE = -I/opt/AMDAPP/include/ -I/opt/acml5.3.1/gfortran64/include/
# LIBS = -L/opt/AMDAPP/lib/x86_64/ -lOpenCL
LIBS = -L/opt/acml5.3.1/gfortran64/lib/ -L/opt/AMDAPP/lib/x86_64 -Llib/x86_64-linux-gnu/ -lOpenCL -lacml -lm
CFLAGS = -O2
TARGET = test
OBJS = test.o hblas.o

$(TARGET): $(OBJS)
	$(CC) -o $(TARGET) $(OBJS) $(LIBS)

.c.o:
	$(CC) $(CFLAGS) $(INCLUDE) -c $<

.cc.o:
	$(CC) $(CFLAGS) $(INCLUDE) -c $<

clean:
	$(RM) $(TARGET) $(OBJS)
